### ISSUE TITLE
getGlide4_SafeKey无法获取问题

### ISSUE THREAD

**Issue by KotlinLan** [Awent/PhotoUtil#1]
你好，请问一下，getGlide4_SafeKey这个方法无法获取缓存文件，如果是默认目录就可以获取，如果是自定义的缓存目录就无法获取，请问是否可以支持在GlideBuilder.setDiskCache()的条件下也支持获取，谢谢！

**Comment by Awent** [comment]
@KotlinLan 我已经添加了，你可以根据你自己的缓存路径来获取缓存文件：

https://github.com/Awent/PhotoUtil/blob/0394a82d4de66ccd3e1ec56a2b646d57ef30341a/photoLibrary/src/main/java/com/awen/image/photopick/util/AppPathUtil.java#L144-L153
